const relacion = [
	{ name: 'Padre', code: 'padre' },
	{ name: 'Madre', code: 'madre' },
	{ name: 'Hijo', code: 'hijo' },
	{ name: 'Hija', code: 'hija' },
	{ name: 'Hermano', code: 'hermano' },
	{ name: 'Hermana', code: 'hermana' },
	{ name: 'Abuelo', code: 'abuelo' },
	{ name: 'Abuela', code: 'abuela' },
	{ name: 'Nieto', code: 'nieto' },
	{ name: 'Nieta', code: 'nieta' },
	{ name: 'Tío', code: 'tio' },
	{ name: 'Tía', code: 'tia' },
	{ name: 'Sobrino', code: 'sobrino' },
	{ name: 'Sobrina', code: 'sobrina' },
	{ name: 'Primo', code: 'primo' },
	{ name: 'Prima', code: 'prima' },
	{ name: 'Yerno', code: 'yerno' },
	{ name: 'Yerna', code: 'yerna' },
	{ name: 'Nuero', code: 'nuero' },
	{ name: 'Nuera', code: 'nuera' },
	{ name: 'Cuñado', code: 'cunado' },
	{ name: 'Cuñada', code: 'cunada' },
	{ name: 'Padre adoptivo', code: 'padre_adoptivo' },
	{ name: 'Madre adoptiva', code: 'madre_adoptiva' },
	{ name: 'Hijo adoptivo', code: 'hijo_adoptivo' },
	{ name: 'Hija adoptiva', code: 'hija_adoptiva' },
	{ name: 'Tutor', code: 'tutor' },
	{ name: 'Tutora', code: 'tutora' },
]

export default relacion
